# Site settings
name: Jahnavi Muddasani
title: Jahnavi Muddasani | Civil Engineer
description: a civil engineer, yearning to work on sustainable development and make energy efficient structures using BIM
url: https://muddasanijahnavi.github.io/
baseurl: ''
email: jmuddasa@purdue.edu
cover: https://muddasanijahnavi.github.io/img/og.png
logo: https://muddasanijahnavi.github.io/technologist.png
resume: https://muddasanijahnavi.github.io/resume.pdf
social:
  - title: email
    url: mailto:jmuddasa@purdue.edu
  # - title: twitter
  #   url: https://twitter.com/bchiang7
  # - title: instagram
  #   url: https://instagram.com/bchiang7
  # - title: codepen
  #   url: http://codepen.io/bchiang7
  # - title: github
  #   url: https://github.com/bchiang7
  - title: linkedin
    url: https://www.linkedin.com/in/jahnavimuddasani/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
